version: '3'
services:
        agate:
                image: obiba/agate:snapshot
                #build: .
                ports:
                        - "8871:8081"
                links:
                        - mongo
                environment:
                        - AGATE_ADMINISTRATOR_PASSWORD=${AGATE_ADMINISTRATOR_PASSWORD}
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
                        - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
                volumes:
                        - ${AGATE_DIR}:/srv
        mongo:
                image: mongo
